function [Vn, Pmusic] = music_spectrum( ...
	Z_phase_matrix, ...
	D_signals, ...
	AoA_range, ...
	steering_function, ...
	steering_arguments ...
)

	Rxx = (Z_phase_matrix * Z_phase_matrix') / size(Z_phase_matrix, 2);
	[V, Dia] = eig(Rxx);
	[~, idx] = sort(diag(Dia), 'descend');
	V = V(:, idx);
	Vn = V(:, D_signals+1:end);
	% Calculate the MUSIC spectrum

	Pmusic = arrayfun(@(steering_angle) (1 / abs( ...
		(steering_function(steering_angle, steering_arguments)' * Vn) * ...
		(Vn' * steering_function(steering_angle, steering_arguments)) ...
		)), AoA_range);

end
