function Z_phase = phase_z( ...
	t, ...
	Z_antenna, ...
	amp_w, ...
	ang_w, ...
	r_w, ...
	phase_w, ...
	lambda_w, ...
	omega_w, ...
	S, ...
	C, ...
	NOISE, ...
	SNR_dB, ...
	ATT ...
)
		% Calculos de amostra I/Q para antena em (0,0)
	I_medido = trapz(t,ref_cos(t, omega_w) ...
		.* signal_r(real(Z_antenna), imag(Z_antenna), t, ...
		amp_w, ang_w, r_w, phase_w, lambda_w, omega_w, ...
		S, C, NOISE, SNR_dB, ATT));
	Q_medido = trapz(t,ref_sin(t, omega_w) ...
		.* signal_r(real(Z_antenna), imag(Z_antenna), t, ...
		amp_w, ang_w, r_w, phase_w, lambda_w, omega_w, ...
		S, C, NOISE, SNR_dB, ATT));

	Z_phase = (omega_w/pi)*(I_medido + i*Q_medido);
end % function
