function steering_vector = steering_circular( ...
	steering_angle, ...
	steering_arguments ...
)

	[ ...
		Rho, ...
		ant_angles, ...
		lambda_w ...
	] = steering_arguments{:};

	% Frank Gross - Smart Antennas for Wireless Communications, pg. 90
	steering_vector = exp(1i*Rho*cos(steering_angle-ant_angles)*2*pi/lambda_w);
end
