function steering_vector = steering_linear( ...
	steering_angle, ...
	steering_arguments ...
)

	[ ...
		d, ...
		N_antenas, ...
		lambda_w ...
	] = steering_arguments{:};

	% Frank Gross - Smart Antennas for Wireless Communications, pg. 69
	steering_vector = exp(1i*d*(0:N_antenas-1)'*cos(steering_angle)*2*pi/lambda_w);
end
